INSERT INTO UNIVERSIDAD(ID, NAME, OWNER) VALUES (99, 'uni1', 'santi');
INSERT INTO UNIVERSIDAD(ID, NAME, OWNER) VALUES (100, 'uni2', 'santi');
INSERT INTO UNIVERSIDAD(ID, NAME, OWNER) VALUES (101, 'uni3', 'santi');
INSERT INTO UNIVERSIDAD(ID, NAME, OWNER) VALUES (102, 'uni4', 'otro2');